# Generated by Django 3.1.6 on 2021-02-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100, verbose_name='país')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
